# Generated by Django 4.2 on 2023-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1200),
        ),
    ]
